### ISSUE TITLE
Add to haskell/actions

### ISSUE THREAD

**Issue by brandonchinn178** [haskell-actions/run-fourmolu#11]
https://github.com/haskell/actions seems like it aims to be a monorepo of all Haskell-related GitHub actions. Maybe it'd be worthwhile to move code there, or otherwise link it?

ref. https://github.com/haskell/actions/issues/81

**Comment by cdepillabout** [comment]
> https://github.com/haskell/actions seems like it aims to be a monorepo of all Haskell-related GitHub actions

Where are you seeing this?  From taking a quick look at the repo, it looks like it only has `hlint`-related actions.

**Comment by brandonchinn178** [comment]
Yes, it currently only has `hlint`-related actions, but the goal seems to be a monorepo: https://github.com/haskell/actions/issues/81#issuecomment-966653017

**Comment by cdepillabout** [comment]
> or otherwise link it

I'm not sure what this would entail, but feel free to send a PR to https://github.com/haskell/actions.  I'm not sure how much time we'd have to help with this, or to maintain code in https://github.com/haskell/actions.

**Comment by brandonchinn178** [comment]
I have access to the new `haskell-actions` org. @cdepillabout if you're good with it, I can transfer `fourmolu-action` to `haskell-actions/run-fourmolu`, and keep you as admin for that repo. It'd be cool to get this action in the "official Haskell github actions" area

**Comment by cdepillabout** [comment]
@brandonchinn178 I don't have a strong opinion either way.  Feel free to make the transfer if that makes the most sense!  Oh, and can you make sure to add @wraithm as an admin as well?

If you do move `fourmolu-action` to that repo, maybe you could reach out to Mark (@mrkkrp) for https://github.com/mrkkrp/ormolu-action to see if he'd be interested in centralizing that as well.

**Comment by brandonchinn178** [comment]
@cdepillabout done! I also renamed the repo so it reads more naturally: `haskell-actions/run-fourmolu` (it shouldn't break existing workflows, as GitHub should redirect appropriately. But I guess we'll see in a couple days). You should have admin access, but I forgot to give myself access; feel free to add me as an admin (or not, happy to keep my hands off)

**Comment by cdepillabout** [comment]
@brandonchinn178 Thanks!  I've added you as an admin!

**Comment by mrkkrp** [comment]
Hey, I have just accepted the invitation to join `haskell-actions`! I'm very much in favor of transferring `ormolu-action` there. I can proceed with that immediately. Is there anything else I should do? Add @cdepillabout as an admin?

**Comment by brandonchinn178** [comment]
I don't think you have to do anything, unless @cdepillabout wants to!

**Comment by mrkkrp** [comment]
Isn't https://github.com/haskell/actions the "official" repository for Haskell actions? https://github.com/haskell-actions seems to be mostly empty. I'm probably missing some context here...

**Comment by mrkkrp** [comment]
> Where are you seeing this? From taking a quick look at the repo, it looks like it only has `hlint`-related actions.

https://github.com/haskell/actions also has `setup` which is what I use to setup Haskell in GitHub actions.

**Comment by mrkkrp** [comment]
I'm all for putting `ormolu-action` into some kind of official collection (and ideally not having to maintain it much), but `haskell-actions` doesn't look like one so far. I'm less keen on just moving things around without any benefit.

**Comment by brandonchinn178** [comment]
@mrkkrp https://github.com/haskell/actions/issues/141#issuecomment-1496934773

**Comment by mrkkrp** [comment]
Okay that looks good. What about renaming? I'm not super convinced that `run-ormolu` is better than `ormolu-action`, but for consistency with `run-fourmolu` it's probably the best moment to rename it...

**Comment by brandonchinn178** [comment]
Up to you 🤷

**Comment by mrkkrp** [comment]
Okay, I transferred it to `haskell-actions` as `run-ormolu`. I don't have admin rights though, so cannot add @cdepillabout as an admin. I imagine he is an admin by default anyway? It would be nice to also get admin rights on that repo to be able to maintain it if necessary.

**Comment by brandonchinn178** [comment]
cc @andreasabel ^

**Comment by mrkkrp** [comment]
I will push a commit adjusting naming, etc. in `run-ormolu` a bit later today.

**Comment by andreasabel** [comment]
@mrkkrp I made you admin of your repo @haskell-actions (don't know why this is a manual step...)
