### ISSUE TITLE
Rewrite README to reference haskell-actions/run-fourmolu instead of fourmolu/fourmolu-action

### ISSUE THREAD

**Issue by cdepillabout** [haskell-actions/run-fourmolu#18]
In #11, we moved from the `fourmolu` organization with a repo name of `fourmolu-action`, to the `haskell-actions` organization with a repo name of `run-fourmolu`.

We need to update the README to reference the new `haskell-actions/run-fourmolu` location.

**Comment by bilalakhter** [comment]
assign me

**Comment by cdepillabout** [comment]
@bilalakhter Assigned!  Thanks for taking a look at this!

**Comment by cdepillabout** [comment]
Fixed in #19 and 0a78989
