### ISSUE TITLE
Suggested checkout@v2 action produces warnings

### ISSUE THREAD

**Issue by BinderDavid** [haskell-actions/run-fourmolu#22]
The snippets in the README.md suggest using `uses: actions/checkout@v2`.
The version should be updated, because this old version now generates the following warning on Github:
```
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```
Updating to `v3` should be sufficient, see: https://github.com/actions/checkout/issues/1047

**Comment by cdepillabout** [comment]
@BinderDavid thanks for the heads up!

Would you be interested in sending a PR fixing this?

**Comment by BinderDavid** [comment]
@cdepillabout Done :)
