### ISSUE TITLE
Add support for specifying a working directory

### ISSUE THREAD

**Issue by jkeuhlen** [haskell-actions/run-fourmolu#28]
fourmolu seems to inherit extension information from the directory where it is launched. For us, this means that running this action in a shared mono-repo "works", but it's missing things like a default TemplateHaskell extension setting and so it misapplies a large portion of formatting. 

e.g. our project layout is something like 
repo
| - .github
  | - workflows 
| - haskell-backend
| - typescript-frontend 

If you run the exact same commands from the haskell-backend directory, everything works great. 

GHA does support a `working-directory` flag for all `run:` blocks: [docs](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrun). That has to be implemented at the library level though to combine it with anything that "uses" a library action. Could something similar be added to this action that essentially does a `cd` into the directory where it should run from first?

**Comment by cdepillabout** [comment]
That sounds reasonable.  I'd be willing to merge in a PR implementing this.

**Comment by jkeuhlen** [comment]
Great. I ended up realizing that I didn't actually need this for my project (we just were failing to check in our .cabal file 🤦 ), but I had the workflow already set up and working so I figured I'd add it anyways in case it's useful in the future: https://github.com/haskell-actions/run-fourmolu/pull/29

**Comment by cdepillabout** [comment]
Fixed in https://github.com/haskell-actions/run-fourmolu/pull/29.  Thanks!
